const createIntent = (id, topic, phrases, keywords, simpleAnswer, deeperExplanation, resourceIds, options = {}) => ({
  id, topic, phrases, keywords, simpleAnswer, deeperExplanation, resourceIds, ...options,
});

export const GUIDE_TOPICS = Object.freeze([
  { id: "loans", label: "Loans", prompt: "Understand EMI, tenure, interest, and prepayment." },
  { id: "investing", label: "Investing", prompt: "Learn SIP, lumpsum investing, returns, and compounding." },
  { id: "goals", label: "Goals", prompt: "Plan education, home, and long-term money goals." },
  { id: "retirement", label: "Retirement", prompt: "Explore retirement corpus and inflation concepts." },
  { id: "deposits", label: "Deposits", prompt: "Compare FD, RD, and PPF learning tools." },
  { id: "tax", label: "Tax basics", prompt: "Understand tax, HRA, GST, gratuity, EPF, and NPS." },
  { id: "health", label: "Financial Health", prompt: "Explore budgeting, savings, debt, and protection habits." },
]);

export const GUIDE_INTENTS = Object.freeze([
  createIntent("loan-emi", "loans", ["how much emi", "calculate emi", "monthly emi", "emi amount"], ["emi", "loan payment", "monthly payment"], "An Equated Monthly Instalment (EMI) is the regular amount used to repay a loan. You can explore how loan amount, interest rate, and tenure change an estimated EMI.", "The calculator uses a reducing-balance loan structure. A longer tenure can lower the estimated monthly amount while interest may be charged for more months.", ["emi", "loansLesson"], { actions: ["Calculate it", "Understand it"], clarificationLabel: "Help me understand EMI" }),
  createIntent("loan-affordability", "loans", ["how much emi can i afford", "can i afford this emi", "loan affordability", "affordable emi"], ["afford", "salary", "income", "comfort"], "I can help you explore loan assumptions and educational eligibility tools, but I do not decide whether a loan is affordable for you. Start by comparing the estimated EMI with your full monthly budget and existing obligations.", "FOINWI’s eligibility tool is illustrative and does not predict lender approval. A complete affordability review can include income stability, expenses, emergency savings, other debt, and lender-specific terms.", ["eligibility", "emi", "loansLesson"], { actions: ["Calculate it", "Understand it"], clarificationLabel: "My EMI feels high" }),
  createIntent("loan-prepayment", "loans", ["prepay my loan", "loan prepayment", "prepayment impact", "pay loan early", "reduce loan early", "close loan faster", "reduce loan payment early", "repay loan sooner", "prepay loan"], ["prepay", "prepayment", "extra payment", "foreclose", "close loan", "repay sooner"], "An extra loan payment may reduce future interest, depending on the loan terms and how the lender applies it. You can explore the trade-off with the prepayment calculator.", "Prepayment effects depend on timing, outstanding balance, loan rate, and any lender charges. The calculator is an educational estimate, not a lender statement.", ["prepayment", "emi", "loansLesson"], { actions: ["Calculate it", "Understand it"], clarificationLabel: "I want to repay early" }),
  createIntent("loan-tenure", "loans", ["loan tenure", "shorter tenure", "longer tenure", "compare tenure"], ["tenure", "years", "months", "repayment period"], "Loan tenure affects both the monthly EMI and total interest. A shorter tenure may raise the estimated monthly payment while reducing the months in which interest is charged.", "There is no universal tenure choice. Compare a few illustrated tenures to understand the payment and interest trade-off before considering your broader budget.", ["emi", "loansLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("loan-interest", "loans", ["why is loan interest high", "total loan interest", "interest on emi"], ["interest", "borrowing cost", "loan cost"], "Total loan interest can rise when the loan amount, rate, or tenure rises. The EMI calculator can show the estimated repayment and interest side by side.", "Interest is normally charged on the outstanding balance. Early instalments can contain more interest than later ones in a reducing-balance loan.", ["emi", "loansLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("loan-eligibility", "loans", ["home loan eligibility", "eligible for home loan", "loan eligibility"], ["eligibility", "qualify", "home loan"], "You can explore an illustrative home-loan eligibility estimate from the inputs shown in the calculator. Actual lender decisions can use additional documents, policies, and checks.", "Eligibility tools simplify lender methods for learning. They do not represent loan approval, a credit decision, or a lender offer.", ["eligibility", "homeJourney"], { actions: ["Calculate it", "Plan it"], clarificationLabel: "I want to understand loan eligibility" }),

  createIntent("invest-sip", "investing", ["sip", "i can invest", "start sip", "sip investment", "how does sip work"], ["sip", "monthly invest", "invest every month", "regular investment"], "A Systematic Investment Plan (SIP) is a way to explore regular market-linked investing. The SIP calculator can illustrate how monthly contributions and assumed returns affect a future value.", "A SIP projection is illustrative, not a promise of market return. It depends on the monthly contribution, time period, assumed return, and the calculator’s stated timing convention.", ["sip", "investingLesson", "wealthJourney"], { actions: ["Calculate it", "Understand it", "Plan it"] }),
  createIntent("invest-lumpsum", "investing", ["lumpsum investment", "one time investment", "invest a lump sum"], ["lumpsum", "one time", "one-time", "large amount"], "A lumpsum is a one-time investment amount. You can use the calculator to explore how a chosen assumed return and period affect an illustrative future value.", "Lumpsum and SIP are different contribution patterns; neither is universally better. The appropriate approach can depend on your goals, timing, risk understanding, and available amount.", ["lumpsum", "investingLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("invest-cagr", "investing", ["what is cagr", "cagr meaning", "what cagr mean", "compound annual growth rate"], ["cagr", "annualised return", "annualized return"], "Compound Annual Growth Rate (CAGR) describes the steady annual rate that would connect a starting value to an ending value over time. It helps compare growth periods, but it does not show every year’s movement.", "CAGR smooths the path between two values. It can be useful for comparing past periods, while actual returns may vary across individual years.", ["cagr", "fundamentals"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("invest-compounding", "investing", ["what is compounding", "how compounding works", "compound interest", "what is compound interest", "explain compound interest", "how compound interest works"], ["compounding", "compound", "returns on returns"], "Compounding means returns may accumulate on the original amount and on earlier returns. Time can make this effect more visible in an illustration.", "Compounding does not remove market uncertainty. A calculator shows a model using an assumed rate; actual investment outcomes can differ.", ["compound", "investingLesson", "fundamentals"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("invest-return-assumption", "investing", ["expected return", "what return should i assume", "return assumption"], ["return", "assumption", "rate of return"], "Return assumptions are inputs for educational projections, not predictions. You can compare more than one assumption to see how sensitive a long-term illustration is.", "A higher assumed return raises the calculated future value, but it is not assured. Consider the calculator as a way to understand scenarios rather than forecast an outcome.", ["sip", "lumpsum", "fundamentals"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("invest-swp", "investing", ["systematic withdrawal", "swp", "withdraw from corpus"], ["swp", "withdrawal", "retirement withdrawal"], "A Systematic Withdrawal Plan (SWP) illustration explores regular withdrawals from a corpus under a constant-return assumption. It can show whether an illustrative corpus lasts through a chosen period.", "Actual fund outcomes can differ due to changing returns, taxes, fees, withdrawal timing, and sequence-of-returns effects. This is educational planning, not an investment instruction.", ["swp", "retirementLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("invest-basics", "investing", ["how investing works", "investing basics", "explain investing", "what is mutual fund", "want start investing", "i want to start investing", "explain sip"], ["investing", "mutual fund", "learn invest"], "Investing means putting money into assets whose value or income can change over time. Start by understanding risk, time horizon, and the difference between an assumed return and an actual outcome.", "FOINWI can explain concepts and show illustrations, but it does not select investments for you. Begin with the fundamentals before deciding whether a calculator is useful for your own learning.", ["fundamentals", "investingLesson"], { actions: ["Understand it"], clarificationLabel: "Understand investing basics" }),

  createIntent("goal-planning", "goals", ["plan a financial goal", "goal planning", "save for a goal"], ["goal", "target", "future plan"], "A financial goal becomes easier to explore when you define a future cost, time horizon, and current savings. The Goal Planner can turn these into an illustrative monthly-saving path.", "Goal planning models are based on stated assumptions such as return and inflation. They can help you understand a gap, but they do not guarantee that a goal will be met.", ["goal", "inflation", "wealthJourney"], { actions: ["Plan it", "Calculate it"] }),
  createIntent("goal-education", "goals", ["child education", "education goal", "save for my child", "save for my child s education"], ["child", "education", "college", "school"], "Education costs may rise over time, so it can help to begin with the expected timing and today’s approximate cost. What would you like to understand first?", "Use the follow-up choices to explore future cost, regular saving, or investing basics. These are educational paths, not a personalised education plan.", ["goal", "educationJourney", "inflation"], { followUps: ["education-need", "education-save", "education-invest"], actions: ["Plan it", "Understand it"] }),
  createIntent("education-need", "goals", ["how much may i need", "education cost", "future education cost"], ["future cost", "education cost"], "The Inflation Calculator can show how a current education cost may change over a selected period. It is a future-cost illustration using the inflation rate you choose.", "Actual education costs vary by institution, course, location, and timing. Treat the result as a planning scenario, then revisit it as your goal becomes clearer.", ["inflation", "goal", "educationJourney"], { actions: ["Calculate it", "Plan it"] }),
  createIntent("education-save", "goals", ["how much should i save regularly", "education monthly savings", "save regularly"], ["monthly savings", "regular saving"], "The Goal Planner can estimate a regular saving amount from a future target, existing savings, timeline, and assumptions. It is an illustration to help you explore the gap.", "The result changes with the selected timeline, inflation, and return assumption. Review the model periodically as your goal and circumstances change.", ["goal", "sip", "educationJourney"], { actions: ["Plan it", "Calculate it"] }),
  createIntent("education-invest", "goals", ["understand investing first", "learn investing for education"], ["investing first", "investing basics"], "Before connecting investing to an education goal, it can help to understand compounding, inflation, and the difference between an assumed return and an actual outcome.", "Learning first does not choose an investment for you. It helps you interpret planning tools and ask clearer questions about long-term goals.", ["fundamentals", "investingLesson", "goal"], { actions: ["Understand it", "Plan it"] }),
  createIntent("goal-home", "goals", ["buy a home", "home down payment", "plan home purchase"], ["home", "down payment", "property"], "A home goal can include a down payment, loan EMI, registration costs, and a timeline. The home journey brings these planning questions together.", "The journey and calculators provide educational estimates. Property costs, lender terms, and personal affordability can vary.", ["homeJourney", "goal", "emi"], { actions: ["Plan it", "Calculate it"] }),
  createIntent("goal-wealth", "goals", ["build wealth", "long term wealth", "wealth building"], ["wealth", "long term", "long-term"], "Wealth building is usually explored through regular saving, goal clarity, time, and understanding investment risk. The Build Wealth Journey offers a structured educational path.", "There is no assured wealth-building outcome. Use the journey and calculators to understand concepts and scenarios, not to select a product.", ["wealthJourney", "sip", "fundamentals"], { actions: ["Plan it", "Understand it"] }),

  createIntent("retirement-start", "retirement", ["plan my retirement", "start retirement planning", "retirement planning"], ["retirement", "retire"], "Retirement planning often begins with the lifestyle you want to support, the years until retirement, and how inflation may change future costs. FOINWI’s tools can help you explore these assumptions.", "A retirement projection is educational and changes with inflation, return assumptions, contribution patterns, and withdrawal needs. It is not a pension promise.", ["retirement", "retirementLesson", "retirementJourney"], { actions: ["Plan it", "Understand it"] }),
  createIntent("retirement-corpus", "retirement", ["retirement corpus", "how much for retirement", "retirement amount"], ["corpus", "retirement amount", "retirement fund"], "A retirement corpus is the amount you may need to support future spending under chosen assumptions. The Retirement Calculator can illustrate this relationship.", "A corpus estimate is sensitive to inflation, years in retirement, and return assumptions. It is useful for scenario learning, not a fixed target.", ["retirement", "inflation", "retirementLesson"], { actions: ["Plan it", "Calculate it"] }),
  createIntent("retirement-inflation", "retirement", ["inflation in retirement", "retirement inflation"], ["inflation", "retirement cost"], "Inflation can raise future living costs, so retirement plans often model costs in future rupees. The Inflation Calculator can make that relationship easier to see.", "Inflation is an assumption in a model, not a fixed future fact. Compare more than one rate to understand how a plan can change.", ["inflation", "retirement", "retirementLesson"], { actions: ["Calculate it", "Understand it"] }),

  createIntent("deposit-fd", "deposits", ["fixed deposit", "fd maturity", "fd calculator"], ["fd", "fixed deposit"], "A Fixed Deposit (FD) calculator can illustrate cumulative maturity when interest is reinvested at the selected rate and compounding frequency.", "Actual bank maturity can differ because of product terms, deposit dates, payout choices, tax/TDS, and premature-withdrawal rules.", ["fd", "moneyBasics"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("deposit-rd", "deposits", ["recurring deposit", "rd maturity", "rd calculator"], ["rd", "recurring deposit"], "A Recurring Deposit (RD) illustration explores fixed monthly deposits using FOINWI’s simplified monthly-compounding model.", "Actual bank RD maturity may differ because banks can use different compounding, deposit-date, missed-instalment, tax, and penalty rules.", ["rd", "savingsLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("deposit-ppf", "deposits", ["public provident fund", "ppf calculator", "ppf"], ["ppf", "public provident fund"], "The PPF calculator can help you explore long-term growth using its stated scheme assumptions. Check official information for current rules and rates before making decisions.", "Government scheme rules, contribution limits, and rates can change. The calculator is educational and should not replace official verification.", ["ppf", "retirementLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("deposit-basics", "deposits", ["how does fd work", "deposit basics", "how do deposits work"], ["deposit", "maturity"], "Deposits are savings products with stated terms. An FD usually begins with one amount, while an RD uses regular deposits over time.", "A deposit calculator can illustrate the arithmetic, but actual bank terms, rates, tax treatment, and withdrawal rules can differ. Review the product’s current terms before acting.", ["fd", "rd", "savingsLesson"], { actions: ["Understand it", "Calculate it"], clarificationLabel: "Understand FD and RD basics" }),

  createIntent("tax-income", "tax", ["income tax basics", "calculate income tax", "income tax", "tax basics", "understand income tax", "how tax works"], ["income tax", "taxable income", "tax basics", "how tax works"], "The Income Tax Calculator can provide an educational estimate using its stated assumptions. Tax outcomes can depend on current rules, income details, deductions, and other circumstances.", "This trial does not provide tax advice or instructions. Use the calculator to understand concepts, and verify current official rules or consult a qualified professional where needed.", ["tax", "taxLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("tax-hra", "tax", ["hra exemption", "house rent allowance", "hra"], ["hra", "house rent allowance"], "The HRA Calculator helps explain the inputs used in a House Rent Allowance exemption illustration. It does not replace tax advice or official verification.", "HRA treatment depends on applicable rules and documented details. Review the calculator’s assumptions and current official guidance.", ["hra", "taxLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("tax-gst", "tax", ["what is gst", "calculate gst", "goods and services tax"], ["gst", "goods services tax"], "The GST Calculator can add or remove Goods and Services Tax from an amount. It is useful for understanding the arithmetic, not for determining compliance.", "GST treatment can depend on the transaction and current rules. Use official sources or qualified support for compliance questions.", ["gst", "taxLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("tax-gratuity", "tax", ["gratuity", "calculate gratuity"], ["gratuity"], "The Gratuity Calculator can illustrate how service period and salary inputs affect an estimate. Employment terms and applicable rules may affect an actual outcome.", "Use the result as an educational estimate. Official eligibility and payment treatment require current rule and employer-policy verification.", ["gratuity", "taxLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("tax-epf", "tax", ["employees provident fund", "epf calculator", "epf"], ["epf", "employees provident fund"], "The EPF Calculator can illustrate how contributions and stated assumptions may build over time. It is not an official account statement.", "EPF rules, rates, and account details can change. Check official information for a current account or statutory question.", ["epf", "retirementLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("tax-nps", "tax", ["national pension system", "nps calculator", "nps"], ["nps", "national pension system"], "The NPS Calculator can illustrate long-term contributions and growth assumptions. It does not select a pension option or predict an outcome.", "NPS rules and outcomes can depend on current scheme terms and assumptions. Use the calculator for educational planning only.", ["nps", "retirementLesson"], { actions: ["Calculate it", "Understand it"] }),

  createIntent("health-budgeting", "health", ["salary comes but nothing remains", "budgeting help", "budget help", "save money", "want save every month", "salary finish every month"], ["budget", "salary", "nothing remains", "expenses", "spending"], "When money seems to disappear, start by understanding where it goes before making a big change. A simple view of essential spending, flexible spending, and saving can make the next step clearer.", "FOINWI does not collect your spending details in this trial. The learning path and Financial Health Score can help you reflect on habits at your own pace.", ["savingsLesson", "health", "moneyBasics"], { actions: ["Understand it", "Check"], clarificationLabel: "Help with my monthly money" }),
  createIntent("health-emergency", "health", ["emergency fund", "emergency savings"], ["emergency fund", "emergency savings", "buffer"], "An emergency fund is money set aside for unexpected costs. Many educational guides discuss building it gradually before relying heavily on long-term plans.", "The right amount can depend on your circumstances, so the trial does not set one for you. Focus first on understanding the role of accessible savings.", ["savingsLesson", "health"], { actions: ["Understand it", "Check"], clarificationLabel: "Understand emergency savings" }),
  createIntent("health-debt", "health", ["debt pressure", "too much debt", "reduce debt", "credit card debt"], ["debt", "loan pressure", "repayment", "credit card"], "Debt pressure can feel overwhelming. Start by understanding each repayment, its interest rate, and the difference between a monthly payment and total borrowing cost.", "FOINWI does not make repayment decisions for you. The debt journey and EMI tools can help you explore the concepts and assumptions involved.", ["debtJourney", "emi", "loansLesson"], { actions: ["Plan it", "Calculate it"], clarificationLabel: "Help me understand debt" }),
  createIntent("health-protection", "health", ["insurance basics", "what is insurance", "protection basics"], ["insurance", "protection", "cover"], "Insurance can help protect against specified financial risks under a policy’s terms. Start by understanding what a policy covers, excludes, and requires before comparing products.", "This trial does not recommend an insurer, policy, or cover amount. The Financial Health Score can help you reflect on protection as one part of your broader money habits.", ["health", "moneyBasics"], { actions: ["Check", "Understand it"], clarificationLabel: "Understand insurance basics" }),
  createIntent("health-score", "health", ["financial health score", "financial health", "check my financial health", "money health"], ["financial health", "health score"], "The Financial Health Score is a separate reflection tool for savings, debt, protection, and planning habits. This trial does not receive or store its answers.", "Open the tool only if you want to complete its questions directly. The Guide will not use those answers in this trial.", ["health"], { actions: ["Check"] }),

  createIntent("compare-sip-fd", "comparison", ["sip vs fd", "fd vs sip"], ["sip", "fd"], "SIP and FD serve different purposes. SIP is useful for exploring regular market-linked investing, while FD is useful for exploring fixed-deposit growth assumptions.", "SIP outcomes can vary with markets; an FD illustration uses a selected deposit rate and product assumptions. Compare the concepts and tools rather than looking for a universal winner.", ["sip", "fd", "investingLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("compare-sip-lumpsum", "comparison", ["sip vs lumpsum", "lumpsum vs sip"], ["sip", "lumpsum"], "SIP and lumpsum are different contribution patterns. SIP explores regular contributions; lumpsum explores one-time investment growth.", "They serve different purposes and neither is universally better. The calculators can help you understand timing, contribution pattern, and assumed-return scenarios.", ["sip", "lumpsum", "fundamentals"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("compare-ppf-sip", "comparison", ["ppf vs sip", "sip vs ppf"], ["ppf", "sip"], "PPF and SIP serve different purposes. PPF is a government-backed scheme with rules that require official verification, while a SIP is a regular market-linked investment approach.", "They differ in return structure, liquidity, risk, and applicable rules. Use the tools to learn the models, not to select one for you.", ["ppf", "sip", "retirementLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("compare-fd-rd", "comparison", ["fd vs rd", "rd vs fd", "compare fd and rd", "rd or fd", "difference between fd and rd", "fd rd difference"], ["fd", "rd"], "FD and RD serve different deposit patterns. An FD begins with one deposit, while an RD uses regular deposits over time.", "FOINWI’s RD model is simplified and actual bank terms may differ. Compare the illustrations to understand contribution timing and compounding assumptions.", ["fd", "rd", "savingsLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("compare-emi-prepayment", "comparison", ["emi vs prepayment", "prepayment vs emi"], ["emi", "prepayment"], "EMI is the regular loan repayment structure; prepayment is an additional payment that may reduce future interest. They work together rather than being alternatives.", "The prepayment tool can illustrate how timing and amount may change future interest. Actual lender terms and charges can differ.", ["emi", "prepayment", "loansLesson"], { actions: ["Calculate it", "Understand it"] }),
  createIntent("compare-cagr-absolute", "comparison", ["cagr vs absolute return", "absolute return vs cagr"], ["cagr", "absolute return"], "Absolute return shows the total change over a period. CAGR converts the same change into an annualised rate for comparison across different durations.", "CAGR smooths a journey into one annual rate, so it does not show volatility or the sequence of yearly returns.", ["cagr", "fundamentals"], { actions: ["Calculate it", "Understand it"] }),

  createIntent("discovery-calculator", "discovery", ["which calculator should i use", "find a calculator", "calculator for me"], ["calculator", "tool"], "Start with the question you want to understand: loans, investing, goals, retirement, deposits, tax basics, or financial health. I can point you toward an educational tool for that topic.", "The calculator hub is useful when you want to browse without guessing. Each calculator explains its assumptions and result type.", ["calculators", "learn"], { actions: ["Explore"] }),
  createIntent("discovery-learning", "discovery", ["what should i learn", "where can i learn finance", "learning path"], ["learn", "lesson", "basics"], "FOINWI Learn starts with money basics, saving, investing, loans, tax, and retirement. Choose a topic you want to understand before going deeper.", "Learning paths are educational and self-paced. They can help you understand calculator terms before using an estimate.", ["learn", "moneyBasics"], { actions: ["Understand it", "Explore"] }),
  createIntent("discovery-journey", "discovery", ["financial journey", "guide me step by step", "journey"], ["journey", "step by step", "path"], "FOINWI Journeys group calculators and learning into a practical topic path. They are educational guides, not personalised financial plans.", "You can explore journeys for wealth building, retirement, debt, family protection, tax, education, and home planning.", ["wealthJourney", "debtJourney", "retirementJourney"], { actions: ["Explore", "Plan it"] }),
  createIntent("discovery-start", "discovery", ["i dont know where to start", "i don't know where to start", "help me with my money", "i am confused", "what should i do first"], ["confused", "start", "help", "where to begin"], "What are you trying to improve?", "Choose a direction below and the Guide will show a fixed educational path. It will not collect your financial details or make a decision for you.", ["savingsLesson", "health"], { followUps: ["health-budgeting", "health-debt", "invest-sip", "goal-planning", "retirement-start", "tax-income", "health-score"], actions: ["Explore"] }),
]);

export const GUIDE_START_OPTIONS = Object.freeze([
  ["Save money", "health-budgeting"],
  ["Reduce debt", "health-debt"],
  ["Start investing", "invest-sip"],
  ["Plan a goal", "goal-planning"],
  ["Plan retirement", "retirement-start"],
  ["Understand taxes", "tax-income"],
  ["Check financial health", "health-score"],
]);
